[project]
name = "huggingface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tavily-python>=0.7.7",
    "wikipedia>=1.4.0",
]
